name: assetutilities
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
      - assetutilities

      - build
      - twine
      - bumpver

      - pyyaml
      - numpy
      - pandas
      - plotly
      - matplotlib
      - chardet
      - python-certifi-win32

      - webcolors
      - xlsxwriter
      - plantuml
      - pytest
      - deepdiff

      - pandoc
      - wkhtmltopdf
      - python-docx

      - excel2img

      # - openpyxl
      # - openpyxl-image-loader

      # - imp
      # - git
      # - popplerqt5 Only available in linux systems
      # - pdfannots
      # - fitz
      # - camelot
      # - tabula
      # - GitPython
      # - PyPDF2
